### ISSUE TITLE
JRuby?

### ISSUE THREAD

**Issue by n-rodriguez** [anirbanmu/str_metrics#22]
Hi there!

Does this gem work with JRuby?

Thank you!

**Comment by anirbanmu** [comment]
I cautiously but optimistically will answer that with a "it should". 😛 I say that based on the fact that the gem uses `ffi` which claims that things should work with no changes on MRI, JRuby & others (https://github.com/ffi/ffi#description).

I will try to add a sanity test pass on JRuby as time allows, so I can answer your question with a surer "yes". Let me know if you end up trying it on JRuby and what the result is.

**Comment by anirbanmu** [comment]
@n-rodriguez added jruby & truffleruby to the automated testing workflow. All the tests pass on both!

see here: https://github.com/anirbanmu/str_metrics/runs/542440170

**Comment by n-rodriguez** [comment]
> @n-rodriguez added jruby & truffleruby to the automated testing workflow. All the tests pass on both!
> 
> see here: https://github.com/anirbanmu/str_metrics/runs/542440170

Awesome! Thank you!
